server:
  port: 8083
spring:
  application:
    name: treasury-service

fxrates:
  api:
    base-url: https://api.fxratesapi.com
    timeout-seconds: 10
management:
  tracing:
    sampling:
      probability: 1.0  # 1.0 = trace 100% request (dev), production nên để 0.1 = 10%

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"





