server:
  port: 8088
spring:
  application:
    name: sell-foreign-service

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: sell_foreign_user
    password: sell_foreign123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        default_schema: SELL_FOREIGN_USER

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
management:
  tracing:
    sampling:
      probability: 1.0  # 1.0 = trace 100% request (dev), production nên để 0.1 = 10%

logging:
  level:
    org.hibernate.SQL: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
